"""initial schema

Revision ID: 123cdeda629d
Revises: 
Create Date: 2026-07-23 23:44:16.980802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123cdeda629d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('role_title', sa.Text(), nullable=False),
    sa.Column('platform', sa.Enum('linkedin', 'naukri', 'campus_drive', 'referral', 'company_website', 'other', name='platform_enum'), nullable=False),
    sa.Column('application_type', sa.Enum('standard', 'campus_drive', 'referral', name='application_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('applied', 'oa_test', 'interview', 'offer', 'rejected', 'withdrawn', name='status_enum'), nullable=False),
    sa.Column('salary_type', sa.Enum('ctc', 'stipend', name='salary_type_enum'), nullable=True),
    sa.Column('salary_fixed_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('salary_variable_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('stipend_monthly', sa.Integer(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('applied_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_applications_user_company', 'applications', ['user_id', 'company_name'], unique=False)
    op.create_index('idx_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('campus_drive_details',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('drive_date', sa.Date(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('shortlist_rounds', sa.Text(), nullable=True),
    sa.Column('placement_cell_contact', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('status_change', 'note', 'email_linked', 'resume_attached', 'custom', name='interaction_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interactions_application', 'interactions', ['application_id', 'occurred_at'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('referral_details',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('referrer_name', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_details')
    op.drop_table('job_descriptions')
    op.drop_index('idx_interactions_application', table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('contacts')
    op.drop_table('campus_drive_details')
    op.drop_index('idx_applications_user_status', table_name='applications')
    op.drop_index('idx_applications_user_company', table_name='applications')
    op.drop_table('applications')
    op.drop_table('resumes')
    op.drop_table('users')
    # ### end Alembic commands ###
